import { uid } from './storage.js'

function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

const profileTemplates = [
  {
    nome: 'Maria Oliveira',
    codigoInterno: 'MO-001',
    login: 'maria.oliveira88@email.com',
    senha: 'MaO!9k$2lPq#',
    twoFA: 'JBSWY3DPEHPK3PXP',
    fornecedor: 'AlphaProfiles',
    dataCompra: daysAgo(40),
    dataCriacaoFacebook: daysAgo(420),
    status: 'em_uso',
    nivelConfianca: 'alto',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '177.45.12.18:8080 (residencial)',
    telefone: '+55 11 9 8642-1199',
    contaAnuncioVinculada: 'AD-7841',
    observacoes: 'Conta antiga com bom histórico, rodando campanha principal de e-commerce.',
    tags: ['premium', 'ecom'],
  },
  {
    nome: 'Bruno Lacerda',
    codigoInterno: 'BL-002',
    login: 'b.lacerda.fb@email.com',
    senha: 'Tr@v3l#2024Br',
    twoFA: 'KRSXG5DJNZTQ====',
    fornecedor: 'AlphaProfiles',
    dataCompra: daysAgo(15),
    dataCriacaoFacebook: daysAgo(180),
    status: 'aquecimento',
    nivelConfianca: 'medio',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '186.101.4.55:8080 (móvel)',
    telefone: '+55 21 9 7311-2882',
    contaAnuncioVinculada: '',
    observacoes: 'Aquecendo com curtidas e grupos. Ainda sem campanhas.',
    tags: ['aquecimento'],
  },
  {
    nome: 'Camila Souza',
    codigoInterno: 'CS-003',
    login: 'camila.s.fb@email.com',
    senha: 'C@m1la!Souza#9',
    twoFA: 'MFRGGZDFMZTWQ===',
    fornecedor: 'TopAccounts',
    dataCompra: daysAgo(3),
    dataCriacaoFacebook: daysAgo(90),
    status: 'novo',
    nivelConfianca: 'medio',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '',
    telefone: '+55 31 9 9402-7711',
    contaAnuncioVinculada: '',
    observacoes: 'Recém comprada, ainda não iniciei aquecimento.',
    tags: ['standard'],
  },
  {
    nome: 'Diego Martins',
    codigoInterno: 'DM-004',
    login: 'diego.m.adv@email.com',
    senha: 'D!3goM@rtins',
    twoFA: 'NBSWY3DPO5XXE3DE',
    fornecedor: 'BetaContas',
    dataCompra: daysAgo(120),
    dataCriacaoFacebook: daysAgo(900),
    status: 'pronto',
    nivelConfianca: 'alto',
    pais: 'Estados Unidos',
    nacionalidade: 'us',
    proxy: '177.78.150.4:8080 (residencial)',
    telefone: '+55 11 9 8112-4421',
    contaAnuncioVinculada: 'AD-3344',
    observacoes: 'Conta aged disponível. Aguardando atribuir BM.',
    tags: ['aged', 'reserva'],
  },
  {
    nome: 'Eduardo Pires',
    codigoInterno: 'EP-005',
    login: 'edu.pires.fb@email.com',
    senha: 'EduP1res$2025',
    twoFA: '',
    fornecedor: 'TopAccounts',
    dataCompra: daysAgo(60),
    dataCriacaoFacebook: daysAgo(300),
    status: 'restricao',
    nivelConfianca: 'baixo',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '177.45.12.42:8080 (residencial)',
    telefone: '+55 47 9 9201-7714',
    contaAnuncioVinculada: 'AD-2210',
    observacoes: 'Recebeu alerta de identidade. Em revisão.',
    tags: ['atencao'],
  },
  {
    nome: 'Fernanda Reis',
    codigoInterno: 'FR-006',
    login: 'fer.reis@email.com',
    senha: 'Fer!Reis#2024',
    twoFA: 'OZSXIIDPMJTW6===',
    fornecedor: 'BetaContas',
    dataCompra: daysAgo(200),
    dataCriacaoFacebook: daysAgo(1300),
    status: 'bloqueado',
    nivelConfianca: 'baixo',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '186.220.1.55:8080 (residencial)',
    telefone: '+55 11 9 7333-2244',
    contaAnuncioVinculada: 'AD-1102',
    observacoes: 'Bloqueada após escala em campanha de infoproduto.',
    tags: ['bloqueio'],
  },
  {
    nome: 'Gabriel Tavares',
    codigoInterno: 'GT-007',
    login: 'gabriel.t.fb@email.com',
    senha: 'G@brielT@v',
    twoFA: 'PB2WG33TMVRXEZLU',
    fornecedor: 'AlphaProfiles',
    dataCompra: daysAgo(8),
    dataCriacaoFacebook: daysAgo(220),
    status: 'aquecimento',
    nivelConfianca: 'medio',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '177.45.13.14:8080 (residencial)',
    telefone: '+55 21 9 9100-2455',
    contaAnuncioVinculada: '',
    observacoes: 'Aquecendo com 2 grupos e marketplace.',
    tags: ['aquecimento'],
  },
  {
    nome: 'Helena Duarte',
    codigoInterno: 'HD-008',
    login: 'helena.d.fb@email.com',
    senha: 'HelenaD!2025',
    twoFA: 'QFRWSY3DPMVTW6===',
    fornecedor: 'TopAccounts',
    dataCompra: daysAgo(90),
    dataCriacaoFacebook: daysAgo(700),
    status: 'em_uso',
    nivelConfianca: 'alto',
    pais: 'Estados Unidos',
    nacionalidade: 'us',
    proxy: '177.220.5.18:8080 (residencial)',
    telefone: '+55 11 9 8745-1166',
    contaAnuncioVinculada: 'AD-9921',
    observacoes: 'Rodando bem em campanha de lead.',
    tags: ['premium', 'leadgen'],
  },
  {
    nome: 'Igor Lima',
    codigoInterno: 'IG-009',
    login: 'igor.l.fb@email.com',
    senha: 'IgorL@4x!',
    twoFA: '',
    fornecedor: 'BetaContas',
    dataCompra: daysAgo(220),
    dataCriacaoFacebook: daysAgo(1800),
    status: 'descartado',
    nivelConfianca: 'baixo',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '',
    telefone: '+55 11 9 5511-7766',
    contaAnuncioVinculada: '',
    observacoes: 'Descartado por excesso de quedas.',
    tags: ['descarte'],
  },
  {
    nome: 'Júlia Rocha',
    codigoInterno: 'JR-010',
    login: 'julia.r.fb@email.com',
    senha: 'JuliaR0ch@!',
    twoFA: 'RZSXG5DJNZTQOIA=',
    fornecedor: 'AlphaProfiles',
    dataCompra: daysAgo(2),
    dataCriacaoFacebook: daysAgo(45),
    status: 'novo',
    nivelConfianca: 'medio',
    pais: 'Brasil',
    nacionalidade: 'br',
    proxy: '',
    telefone: '+55 31 9 9777-3322',
    contaAnuncioVinculada: '',
    observacoes: 'Conta nova, aguardando entrar em aquecimento.',
    tags: ['standard'],
  },
]

const bmTemplates = [
  {
    nome: 'BM Comercial #1',
    bmId: '1029384756102938',
    perfilDono: 'Maria Oliveira',
    perfisVinculados: ['Maria Oliveira', 'Helena Duarte'],
    contasAnuncio: [
      { nome: 'Loja Principal · Conta 01', id: 'AD-7841', status: 'usando', qualidade: 'escala', tier: 't1', moeda: 'brl', observacao: 'Conta principal de escala' },
      { nome: 'Loja Principal · Conta 02', id: 'AD-9921', status: 'usando', qualidade: 'boa', tier: 't2', moeda: 'brl', observacao: '' },
    ],
    metodoPagamento: true,
    limiteDiario: 'R$ 5.000',
    status: 'em_uso',
    verificacao: 'verificada',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: ['lojaprincipal.com.br'],
    paginas: ['Loja Principal Oficial'],
    observacoes: 'BM forte. Mantém limite alto.',
    tags: ['premium', 'ecom'],
  },
  {
    nome: 'BM Reserva #2',
    bmId: '2938475610293847',
    perfilDono: 'Diego Martins',
    perfisVinculados: ['Diego Martins'],
    contasAnuncio: [
      { nome: 'Reserva Comercial · 01', id: 'AD-3344', status: 'preparacao', qualidade: 'iniciante', tier: 't2', moeda: 'brl', observacao: '' },
    ],
    metodoPagamento: true,
    limiteDiario: 'R$ 1.500',
    status: 'pronta',
    verificacao: 'em_analise',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: [],
    paginas: ['Reserva Oficial'],
    observacoes: 'Pronta para entrar caso a primária caia.',
    tags: ['reserva'],
  },
  {
    nome: 'BM Aquecimento Beta',
    bmId: '3847561029384756',
    perfilDono: 'Bruno Lacerda',
    perfisVinculados: ['Bruno Lacerda', 'Gabriel Tavares'],
    contasAnuncio: [
      { nome: 'Beta Aquecimento 01', id: 'AD-5501', status: 'aquecendo', qualidade: 'iniciante', tier: 't3', moeda: 'brl', observacao: 'Aguardando dom verificado' },
      { nome: 'Beta Aquecimento 02', id: 'AD-5502', status: 'aquecendo', qualidade: 'iniciante', tier: 'low', moeda: 'brl', observacao: '' },
    ],
    metodoPagamento: false,
    limiteDiario: '',
    status: 'preparacao',
    verificacao: 'nao_verificada',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: [],
    paginas: [],
    observacoes: 'Em preparação. Vincular método de pagamento.',
    tags: ['aquecimento'],
  },
  {
    nome: 'BM Lead Pro',
    bmId: '4756102938475610',
    perfilDono: 'Helena Duarte',
    perfisVinculados: ['Helena Duarte'],
    contasAnuncio: [
      { nome: 'Lead Pro · Principal', id: 'AD-9921', status: 'usando', qualidade: 'mediana', tier: 't2', moeda: 'usd', observacao: 'CTR oscilando' },
      { nome: 'Lead Pro · Lançamento', id: 'AD-7702', status: 'usando', qualidade: 'boa', tier: 't1', moeda: 'usd', observacao: '' },
      { nome: 'Lead Pro · Reativação', id: 'AD-7703', status: 'usando', qualidade: 'ruim', tier: 't3', moeda: 'usd', observacao: 'Custo por lead alto' },
    ],
    metodoPagamento: true,
    limiteDiario: 'US$ 2,500',
    status: 'em_uso',
    verificacao: 'verificada',
    pais: 'Estados Unidos',
    nacionalidade: 'us',
    dominios: ['leadpro.com.br'],
    paginas: ['Lead Pro'],
    observacoes: 'Operando captação de leads.',
    tags: ['leadgen'],
  },
  {
    nome: 'BM Restrita Ômega',
    bmId: '5610293847561029',
    perfilDono: 'Eduardo Pires',
    perfisVinculados: ['Eduardo Pires'],
    contasAnuncio: [
      { nome: 'Ômega · Reserva', id: 'AD-2210', status: 'usando', qualidade: 'ruim', tier: 't3', moeda: 'brl', observacao: 'Recurso enviado' },
      { nome: 'Ômega · Backup', id: 'AD-2211', status: 'usando', qualidade: 'ruim', tier: 't4', moeda: 'brl', observacao: 'Bloqueada por política' },
    ],
    metodoPagamento: true,
    limiteDiario: 'R$ 800',
    status: 'restricao',
    verificacao: 'nao_verificada',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: ['ofertasomega.com'],
    paginas: ['Ofertas Ômega'],
    observacoes: 'Recebeu aviso de pagamento. Recurso enviado.',
    tags: ['atencao'],
  },
  {
    nome: 'BM Em Análise Sigma',
    bmId: '6102938475610293',
    perfilDono: 'Camila Souza',
    perfisVinculados: ['Camila Souza'],
    contasAnuncio: [
      { nome: 'Sigma · Inicial', id: 'AD-8801', status: 'criada', qualidade: 'iniciante', tier: 'low', moeda: 'brl', observacao: '' },
    ],
    metodoPagamento: false,
    limiteDiario: '',
    status: 'analise',
    verificacao: 'em_analise',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: [],
    paginas: [],
    observacoes: 'BM nova, em verificação inicial pelo Meta.',
    tags: ['novidade'],
  },
  {
    nome: 'BM Bloqueada Delta',
    bmId: '7561029384756102',
    perfilDono: 'Fernanda Reis',
    perfisVinculados: ['Fernanda Reis'],
    contasAnuncio: [
      { nome: 'Delta · Principal', id: 'AD-1102', status: 'usando', qualidade: 'ruim', tier: 't4', moeda: 'brl', observacao: 'Sem recurso' },
      { nome: 'Delta · Backup', id: 'AD-1103', status: 'usando', qualidade: 'ruim', tier: 'low', moeda: 'brl', observacao: '' },
    ],
    metodoPagamento: true,
    limiteDiario: 'R$ 0',
    status: 'bloqueada',
    verificacao: 'nao_verificada',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: ['deltaofertas.com'],
    paginas: ['Delta Ofertas'],
    observacoes: 'Bloqueada por política de pagamento. Sem recurso possível.',
    tags: ['bloqueio'],
  },
  {
    nome: 'BM Nova Phi',
    bmId: '8475610293847561',
    perfilDono: 'Júlia Rocha',
    perfisVinculados: ['Júlia Rocha'],
    contasAnuncio: [],
    metodoPagamento: false,
    limiteDiario: '',
    status: 'nova',
    verificacao: 'nao_verificada',
    pais: 'Brasil',
    nacionalidade: 'br',
    dominios: [],
    paginas: [],
    observacoes: 'BM recém-criada.',
    tags: ['standard'],
  },
]

export function buildMockData() {
  const now = new Date().toISOString()

  const profiles = profileTemplates.map((t) => ({
    id: uid('p'),
    nome: t.nome,
    codigoInterno: t.codigoInterno,
    login: t.login,
    senha: t.senha,
    twoFA: t.twoFA || '',
    fornecedor: t.fornecedor,
    dataCompra: t.dataCompra,
    dataCriacaoFacebook: t.dataCriacaoFacebook,
    status: t.status,
    nivelConfianca: t.nivelConfianca,
    pais: t.pais,
    nacionalidade: t.nacionalidade || 'br',
    proxy: t.proxy || '',
    telefone: t.telefone || '',
    bmVinculada: '',
    contaAnuncioVinculada: t.contaAnuncioVinculada || '',
    observacoes: t.observacoes,
    tags: t.tags,
    historico: [
      {
        id: uid('h'),
        tipo: 'criado',
        descricao: `Perfil cadastrado com status "${t.status}".`,
        autor: 'admin',
        data: t.dataCompra,
      },
    ],
    notas: [],
    createdAt: t.dataCompra,
    updatedAt: now,
  }))

  // mapeia donos por nome
  const profileByName = Object.fromEntries(profiles.map((p) => [p.nome, p]))

  const bms = bmTemplates.map((t) => {
    const dono = profileByName[t.perfilDono]
    const perfilDonoId = dono?.id || ''
    const perfisVinculadosIds = t.perfisVinculados
      .map((nome) => profileByName[nome]?.id)
      .filter(Boolean)
    const createdAt = daysAgo(Math.floor(Math.random() * 90) + 10)

    return {
      id: uid('b'),
      nome: t.nome,
      bmId: t.bmId,
      perfilDono: perfilDonoId,
      perfisVinculados: perfisVinculadosIds,
      contasAnuncio: t.contasAnuncio,
      metodoPagamento: t.metodoPagamento,
      limiteDiario: t.limiteDiario,
      status: t.status,
      verificacao: t.verificacao || 'nao_verificada',
      pais: t.pais,
      nacionalidade: t.nacionalidade || 'br',
      dominios: t.dominios,
      paginas: t.paginas,
      observacoes: t.observacoes,
      tags: t.tags,
      historico: [
        {
          id: uid('h'),
          tipo: 'criado',
          descricao: `BM cadastrada com status "${t.status}".`,
          autor: 'admin',
          data: createdAt,
        },
      ],
      notas: [],
      createdAt,
      updatedAt: now,
    }
  })

  // Vincula perfis a uma BM apropriada (perfil_dono → BM)
  bms.forEach((bm) => {
    bm.perfisVinculados.forEach((perfilId) => {
      const p = profiles.find((x) => x.id === perfilId)
      if (p && !p.bmVinculada) p.bmVinculada = bm.id
    })
  })

  return { profiles, bms }
}
